name: sakoku

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sakoku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run sakoku
        uses: smartcrabai/sakoku@836620700bc1537d58a1be0dae8fa8ac54767673 # v0.3.0
